[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solanadapp = "4BTeVU7EXaDVCvYbZiWLgYinhiR4iJL7hhyRzwdP2au5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "LOG_LEVEL=debug bun test --timeout 300000"
